using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace WLED_MQTT
{
    public class WledEffect
    {
        [JsonProperty(PropertyName = "effectName")]
        public string EffectName { get; set; }

        [JsonProperty(PropertyName = "effectId")]
        public int EffectId { get; set; }
    }

    public static class WledEffectList
    {
        public static List<WledEffect> Create()
        {
            return new List<WledEffect>
            {
                new WledEffect { EffectName = "Static", EffectId = 0  },
                new WledEffect { EffectName = "Blink", EffectId = 1 },
                new WledEffect { EffectName = "Breath", EffectId = 2 },
                new WledEffect { EffectName = "Color Wipe", EffectId = 3 },
                new WledEffect { EffectName = "Color Wipe_random", EffectId = 4 },
                new WledEffect { EffectName = "Random Color", EffectId = 5 },
                new WledEffect { EffectName = "Color Sweep", EffectId = 6 },
                new WledEffect { EffectName = "Dynamic", EffectId = 7 },
                new WledEffect { EffectName = "Rainbow", EffectId = 8 },
                new WledEffect { EffectName = "Rainbow Cycle", EffectId = 9 },
                new WledEffect { EffectName = "Scan", EffectId = 10 },
                new WledEffect { EffectName = "Dual Scan", EffectId = 11 },
                new WledEffect { EffectName = "Fade", EffectId = 12 },
                new WledEffect { EffectName = "Theater Chase", EffectId = 13 },
                new WledEffect { EffectName = "Theater Chase Rainbow", EffectId = 14 },
                new WledEffect { EffectName = "Running Lights", EffectId = 15 },
                new WledEffect { EffectName = "Saw", EffectId = 16 },
                new WledEffect { EffectName = "Twinkle", EffectId = 17 },
                new WledEffect { EffectName = "Dissolve", EffectId = 18 },
                new WledEffect { EffectName = "Dissolve Random", EffectId = 19 },
                new WledEffect { EffectName = "Sparkle", EffectId = 20 },
                new WledEffect { EffectName = "Flash Sparkle", EffectId = 21 },
                new WledEffect { EffectName = "Hyper Sparkle", EffectId = 22 },
                new WledEffect { EffectName = "Strobe", EffectId = 23 },
                new WledEffect { EffectName = "Strobe Rainbow", EffectId = 24 },
                new WledEffect { EffectName = "Multi Strobe", EffectId = 25 },
                new WledEffect { EffectName = "Blink Rainbow", EffectId = 26 },
                new WledEffect { EffectName = "Android", EffectId = 27 },
                new WledEffect { EffectName = "Chase Color", EffectId = 28 },
                new WledEffect { EffectName = "Chase Random", EffectId = 29 },
                new WledEffect { EffectName = "Chase Rainbow", EffectId = 30 },
                new WledEffect { EffectName = "Chase Flash", EffectId = 31 },
                new WledEffect { EffectName = "Chase Flash Random", EffectId = 32 },
                new WledEffect { EffectName = "Chase Rainbow White", EffectId = 33 },
                new WledEffect { EffectName = "Colorful", EffectId = 34 },
                new WledEffect { EffectName = "Traffic Light", EffectId = 35 },
                new WledEffect { EffectName = "Color Sweep Random", EffectId = 36 },
                new WledEffect { EffectName = "Running Color", EffectId = 37 },
                new WledEffect { EffectName = "Aurora", EffectId = 38 },
                new WledEffect { EffectName = "Running Random", EffectId = 39 },
                new WledEffect { EffectName = "Larson Scanner", EffectId = 40 },
                new WledEffect { EffectName = "Comet", EffectId = 41 },
                new WledEffect { EffectName = "Fireworks", EffectId = 42 },
                new WledEffect { EffectName = "Rain", EffectId = 43 },
                new WledEffect { EffectName = "Tetrix", EffectId = 44 },
                new WledEffect { EffectName = "Fire Flicker", EffectId = 45 },
                new WledEffect { EffectName = "Gradient", EffectId = 46 },
                new WledEffect { EffectName = "Loading", EffectId = 47 },
                new WledEffect { EffectName = "Police", EffectId = 48 },
                new WledEffect { EffectName = "Fairy", EffectId = 49 },
                new WledEffect { EffectName = "Two Dots", EffectId = 50 },
                new WledEffect { EffectName = "Fairytwinkle", EffectId = 51 },
                new WledEffect { EffectName = "Running Dual", EffectId = 52 },
                new WledEffect { EffectName = "Halloween", EffectId = 53 },
                new WledEffect { EffectName = "Tricolor Chase", EffectId = 54 },
                new WledEffect { EffectName = "Tricolor Wipe", EffectId = 55 },
                new WledEffect { EffectName = "Tricolor Fade", EffectId = 56 },
                new WledEffect { EffectName = "Lightning", EffectId = 57 },
                new WledEffect { EffectName = "Icu", EffectId = 58 },
                new WledEffect { EffectName = "Multi Comet", EffectId = 59 },
                new WledEffect { EffectName = "Dual Larson Scanner", EffectId = 60 },
                new WledEffect { EffectName = "Random Chase", EffectId = 61 },
                new WledEffect { EffectName = "Oscillate", EffectId = 62 },
                new WledEffect { EffectName = "Pride 2015", EffectId = 63 },
                new WledEffect { EffectName = "Juggle", EffectId = 64 },
                new WledEffect { EffectName = "Palette", EffectId = 65 },
                new WledEffect { EffectName = "Fire 2012", EffectId = 66 },
                new WledEffect { EffectName = "Colorwaves", EffectId = 67 },
                new WledEffect { EffectName = "Bpm", EffectId = 68 },
                new WledEffect { EffectName = "Fillnoise8", EffectId = 69 },
                new WledEffect { EffectName = "Noise16 (1)", EffectId = 70 },
                new WledEffect { EffectName = "Noise16 (2)", EffectId = 71 },
                new WledEffect { EffectName = "Noise16 (3)", EffectId = 72 },
                new WledEffect { EffectName = "Noise16 (4)", EffectId = 73 },
                new WledEffect { EffectName = "Colortwinkle", EffectId = 74 },
                new WledEffect { EffectName = "Lake", EffectId = 75 },
                new WledEffect { EffectName = "Meteor", EffectId = 76 },
                new WledEffect { EffectName = "Meteor Smooth", EffectId = 77 },
                new WledEffect { EffectName = "Railway", EffectId = 78 },
                new WledEffect { EffectName = "Ripple", EffectId = 79 },
                new WledEffect { EffectName = "Twinklefox", EffectId = 80 },
                new WledEffect { EffectName = "Twinklecat", EffectId = 81 },
                new WledEffect { EffectName = "Halloween Eyes", EffectId = 82 },
                new WledEffect { EffectName = "Static Pattern", EffectId = 83 },
                new WledEffect { EffectName = "Tri Static Pattern", EffectId = 84 },
                new WledEffect { EffectName = "Spots", EffectId = 85 },
                new WledEffect { EffectName = "Spots Fade", EffectId = 86 },
                new WledEffect { EffectName = "Glitter", EffectId = 87 },
                new WledEffect { EffectName = "Candle", EffectId = 88 },
                new WledEffect { EffectName = "Starburst", EffectId = 89 },
                new WledEffect { EffectName = "Exploding Fireworks", EffectId = 90 },
                new WledEffect { EffectName = "Bouncingballs", EffectId = 91 },
                new WledEffect { EffectName = "Sinelon", EffectId = 92 },
                new WledEffect { EffectName = "Sinelon Dual", EffectId = 93 },
                new WledEffect { EffectName = "Sinelon Rainbow", EffectId = 94 },
                new WledEffect { EffectName = "Popcorn", EffectId = 95 },
                new WledEffect { EffectName = "Drip", EffectId = 96 },
                new WledEffect { EffectName = "Plasma", EffectId = 97 },
                new WledEffect { EffectName = "Percent", EffectId = 98 },
                new WledEffect { EffectName = "Ripple Rainbow", EffectId = 99 },
                new WledEffect { EffectName = "Heartbeat", EffectId = 100 },
                new WledEffect { EffectName = "Pacifica", EffectId = 101 },
                new WledEffect { EffectName = "Candle Multi", EffectId = 102 },
                new WledEffect { EffectName = "Solid Glitter", EffectId = 103 },
                new WledEffect { EffectName = "Sunrise", EffectId = 104 },
                new WledEffect { EffectName = "Phased", EffectId = 105 },
                new WledEffect { EffectName = "Twinkleup", EffectId = 106 },
                new WledEffect { EffectName = "Noisepal", EffectId = 107 },
                new WledEffect { EffectName = "Sinewave", EffectId = 108 },
                new WledEffect { EffectName = "Phasednoise", EffectId = 109 },
                new WledEffect { EffectName = "Flow", EffectId = 110 },
                new WledEffect { EffectName = "Chunchun", EffectId = 111 },
                new WledEffect { EffectName = "Dancing Shadows", EffectId = 112 },
                new WledEffect { EffectName = "Washing Machine", EffectId = 113 },
                new WledEffect { EffectName = "Candy Cane", EffectId = 114 },
                new WledEffect { EffectName = "Blends", EffectId = 115 },
                new WledEffect { EffectName = "TV Simulator", EffectId = 116 },
                new WledEffect { EffectName = "Dynamic Smooth", EffectId = 117 },
            }
            .OrderBy(e => e.EffectName)
            .ToList();
        }
    }
}
